fixing assembly delete from project
lcacollect/project-backend pull request #21
Opened 2024-01-18 12:10 UTC by EgiLuk

2024-01-18 13:49 UTC, tumaitelaura approved these changes
good job :)

2024-01-19 14:14 UTC, jaa-itminds requested changes
Thanks for contributing! 

Besides my tiny comment also an FYI; the base branch should be switched to `stage` and not directly to `main`, since we then deploy it to our testing environment.

2024-01-19 14:14 UTC, jaa-itminds commented on src/core/federation.py
>      """Delete assembly"""
Tiny thing here; the comment should be updated to match the new functionality :)

2024-02-01 14:57 UTC, jaa-itminds approved these changes

2024-02-01 14:57 UTC, merged